/**
 * Challenge Box
 * Challenge Box API
 *
 * OpenAPI spec version: 1.0
 * Contact: beispielemail@beispiel.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Task } from './task';


export interface Venturer { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    sportScore?: number;
    nutritionScore?: number;
    mentalScore?: number;
    tasks?: Array<Task>;
    completeScore?: number;
}