version: "3.4"

services:
  node:
    container_name: challengebox-frontend-node_dev
    build:
      context: .
      target: runtime
    environment:
      - NODE_ENV=development
    ports:
      - "8100:8100"
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: bash -c "npm i && ionic serve --no-open"